export const ceoFullNames: string[] = [
  "Jonathan B. Nelson",
  "Frederick W. Smith",
  "Fred T. Bauer",
  "Leslie H. Wexner",
  "Robert L. Waltrip",
  "Peter B. Orthwein",
  "Alan B. Miller",
  "Lawrence J. Ellison",
  "Clarence L. Werner",
  "Robert I. Toll",
  "Gerald B. Shreiber",
  "Charles Robert Schwab",
  "Alan S. McKim",
  "James H. Herbert, II",
  "Jean Madar",
  "Steven J. Hilton",
  "William Robert Berkley",
  "Charles W. Hull",
  "Robert J. Shillman",
  "George Victor Joseph",
  "Timothy S. Duncan",
  "Paul M. Rady",
  "David L. Liniger",
  "Bassil I. Dahiyat, Ph.D.",
  "Derek T. Chalmers, D.Sc., Ph.D.",
  "Scott L. Tarriff",
  "Lee Chen",
  "Chad R. Richison",
  "Yongfeng Zhang, Ph.D.",
  "Stephen D. Neeleman",
  "Darryl Graham Andrew Rawlings",
  "Patrizio Vinciarelli, Ph.D.",
  "Norman H. Asbjornson",
  "Christopher H. Volk",
  "Mary B. Fedewa",
  "Fred P. Lampropoulos",
  "Aaron P. Graft",
  "James R. Brickman",
  "Guy Sella",
  "Arlen Dale Nordhagen",
  "David A. Harrell",
  "Michael Thomas Heffernan, B.S. Pharm, R.Ph.",
  "Steven L. Berman",
  "Leonard S. Schleifer, M.D., Ph.D.",
  "Milton Cooper",
  "Jonathan Laurence Steinberg",
  "Lynn Michelle Jurich",
  "Edward Harris Fenster",
  "Aart J. de Geus",
  "Sherwin I. Seligsohn",
  "Warren Eisenberg",
  "Leonard Joseph Feinstein",
  "Howard D. Schultz",
  "Adam Elsesser",
  "Michael Patrick Kehoe",
  "Scott D. Cook",
  "Jure Sola",
  "John H. Schnatter",
  "Richard A. Hayne",
  "Alex Vetter",
  "Irwin David Simon",
  "Michael L. Baur",
  "Hamid R. Moghadam",
  "Dallas B. Tanner",
  "George C. Zoley, Ph.D.",
  "Richard D. Fairbank",
  "Mark E. Speese",
  "James J. Truchard, Ph.D.",
  "Terry J. Rosen, Ph.D.",
  "D. McDonald Armstrong",
  "Andrew J. Paul",
  "Charles William Ergen",
  "Roger J. Medel, M.D.",
  "C. James Koch",
  "Kenneth D. Tuchman",
  "Paul Marciano",
  "Edward Joseph Wehmer",
  "Mark D. Millett",
  "George F. Colony",
  "Mark D. Dankberg",
  "Paul J. Sarvadi",
  "Michael J. Brown, M.Sc., MSc",
  "Jeffrey P. Bezos",
  "Joel S. Marcus, CPA, J.D.",
  "Walter S. Woltosz, M.A.S., M.S.",
  "Simon Raab",
  "B. Scott Smith",
  "O. Bruton Smith",
  "D. James Bidzos",
  "Patricia Gallup",
  "Thomas Kendall Hunt",
  "Andrew C. Florance",
  "Jen-Hsun Huang",
  "Robert Y. Greenberg",
  "Martine A. Rothblatt, J.D., M.B.A., Ph.D.",
  "Pradeep Sindhu, Ph.D.",
  "Anil K. Singhal",
  "Vincent K. McMahon",
  "F. Thomson Leighton",
  "Thomas Sandgaard",
  "Robert A. Frist, Jr.",
  "Robert P. LoCascio",
  "Min-Hwan Kao, Ph.D.",
  "Randall A. Lipps",
  "Patrick W. Smith",
  "Kevin Cronin Clark",
  "John K. Kibarian, Ph.D.",
  "Daniel A. DeMatteo",
  "Joseph K. Belanoff, M.D.",
  "David Schaeffer, Ph.D.",
  "Wilmot Reed Hastings, Jr.",
  "Stephen A. Wynn",
  "Steven D. Fredrickson",
  "Kevin P. Stevenson",
  "C. S. Lo",
  "David Jeff Noble",
  "Marc R. Benioff",
  "Richard Mitchell McVey",
  "Lawrence Edward Page",
  "Wayne Kent Taylor",
  "Kenneth M. Woolley",
  "Mark W. Brugger",
  "Joseph John DePaolo",
  "Michael R. Hsing",
  "Edward K. Aldag, Jr.",
  "Keith G. Myers",
  "Rohit Kapoor",
  "Jeffrey C. Sprecher",
  "Colin M. Angle",
  "John W. Allison",
  "Kevin A. Plank",
  "William P. Angrick, III",
  "Mihael H. Polymeropoulos, M.D.",
  "Jay S. Sidhu",
  "Mark Elliot Zuckerberg",
  "David C. Paul",
  "Frederic B. Luddy",
  "Thomas G. Vellios",
  "Rodney Hershberger",
  "Robert A. Ortenzio",
  "Valentin P. Gapontsev, Ph.D.",
  "Patrick J. McEnany",
  "Fuad El-Hibri",
  "Thomas Pechy Peterffy",
  "Gregory Strakosch",
  "Bruce C. Cozadd",
  "Joseph E. Kiani",
  "Christopher R. Christensen",
  "David Tom Mitchell",
  "Pareshbhai Suryakant Patel",
  "Douglas R. Lebda",
  "Ken Xie",
  "Peter M. Hecht, Ph.D.",
  "Steven W. Streit",
  "Kishore Seendripu, Ph.D.",
  "Judson Taft Bergman",
  "William C. Crager",
  "Mike Fushing Chang, Ph.D.",
  "Elon R. Musk",
  "Ernest Sylvan Rady",
  "Rajinder P. Singh",
  "Jack A. Khattar",
  "Christopher Pappas",
  "Arkadiy Dobkin",
  "Joseph Wm. Foran",
  "Randy A. Foutch",
  "Jeremy Stoppelman",
  "Stephen Kaufer",
  "Sander Van Deventer, M.D., Ph.D.",
];
